#!/bin/bash
# for making the bridge-nf-bds patches
# 18 September 2002: removed net/Config.in
# 9 October 2002: added include/linux/netfilter_bridge.h
# 19 October 2002: removed ip_output.c

export FROM=linux-2.4.20
export TO=linux-2.4.20-patch
export FILE=bridge-nf-0.0.10-against-2.4.20.diff

echo "bridge-nf-0.0.10-against-2.4.20 - 07 December 2002" >$FILE
echo >>$FILE

diff -urN $FROM/include/linux/netfilter.h $TO/include/linux/netfilter.h >> $FILE
diff -urN $FROM/include/linux/netfilter_ipv4.h $TO/include/linux/netfilter_ipv4.h >> $FILE
diff -urN $FROM/include/linux/netfilter_bridge.h $TO/include/linux/netfilter_bridge.h >> $FILE
diff -urN $FROM/include/linux/skbuff.h $TO/include/linux/skbuff.h >> $FILE

diff -urN $FROM/net/bridge/br.c $TO/net/bridge/br.c >> $FILE
diff -urN $FROM/net/bridge/br_forward.c $TO/net/bridge/br_forward.c >> $FILE
diff -urN $FROM/net/bridge/br_input.c $TO/net/bridge/br_input.c >> $FILE
diff -urN $FROM/net/bridge/br_private.h $TO/net/bridge/br_private.h >> $FILE
diff -urN $FROM/net/bridge/Makefile $TO/net/bridge/Makefile >> $FILE
diff -urN $FROM/net/core/netfilter.c $TO/net/core/netfilter.c >> $FILE
diff -urN $FROM/net/core/skbuff.c $TO/net/core/skbuff.c >> $FILE
diff -urN $FROM/net/ipv4/netfilter/ip_tables.c $TO/net/ipv4/netfilter/ip_tables.c >> $FILE
diff -urN $FROM/net/ipv4/ip_output.c $TO/net/ipv4/ip_output.c >> $FILE
diff -urN $FROM/net/ipv4/netfilter/ipt_LOG.c $TO/net/ipv4/netfilter/ipt_LOG.c >> $FILE
diff -urN /dev/null $TO/net/bridge/br_netfilter.c >> $FILE
