#!/bin/bash
# Used to make incremental diffs for ebtables userspace
# 31 July 2002, added mark match/target

export FROM=/ebtables-cvs/ebtables2/userspace/ebtables2/
export TO=ebtables-v2.0.2
export FILE=iets.diff

diff -urN $FROM/Makefile $TO/Makefile > $FILE
diff -urN $FROM/ebtables.c $TO/ebtables.c >> $FILE
diff -urN $FROM/getethertype.c $TO/getethertype.c >> $FILE
diff -urN $FROM/communication.c $TO/communication.c >> $FILE
diff -urN $FROM/extensions/ebt_redirect.c $TO/extensions/ebt_redirect.c >> $FILE
diff -urN $FROM/extensions/ebtable_broute.c $TO/extensions/ebtable_broute.c >> $FILE
diff -urN $FROM/extensions/ebt_nat.c $TO/extensions/ebt_nat.c >> $FILE
diff -urN $FROM/extensions/ebt_ip.c $TO/extensions/ebt_ip.c >> $FILE
diff -urN $FROM/extensions/ebt_arp.c $TO/extensions/ebt_arp.c >> $FILE
diff -urN $FROM/extensions/ebt_vlan.c $TO/extensions/ebt_vlan.c >> $FILE
diff -urN $FROM/extensions/ebt_log.c $TO/extensions/ebt_log.c >> $FILE
diff -urN $FROM/extensions/ebt_standard.c $TO/extensions/ebt_standard.c >> $FILE
diff -urN $FROM/extensions/ebtable_filter.c $TO/extensions/ebtable_filter.c >> $FILE
diff -urN $FROM/extensions/ebtable_nat.c $TO/extensions/ebtable_nat.c >> $FILE
diff -urN $FROM/extensions/ebt_mark.c $TO/extensions/ebt_mark.c >> $FILE
diff -urN $FROM/extensions/ebt_mark_m.c $TO/extensions/ebt_mark_m.c >> $FILE
diff -urN $FROM/extensions/Makefile $TO/extensions/Makefile >> $FILE
diff -urN $FROM/COPYING $TO/COPYING >> $FILE
diff -urN $FROM/THANKS $TO/THANKS >> $FILE
diff -urN $FROM/ChangeLog $TO/ChangeLog >> $FILE
diff -urN $FROM/ebtables.8 $TO/ebtables.8 >> $FILE
diff -urN $FROM/ethertypes $TO/ethertypes >> $FILE
diff -urN $FROM/include/ebtables_u.h $TO/include/ebtables_u.h >> $FILE
diff -urN $FROM/include/ethernetdb.h $TO/include/ethernetdb.h >> $FILE
